---
title: "Homework3"
date: "2019Äê12ÔÂ16ÈÕ"
output: html_document
---

Problem 3

```{r}
library(tidyverse)
```


(a)
```{r}
data1=read_table("Sensory.dat.txt",skip = 1)
data1=data1[-1,]
print(data1)
```


(b)
```{r}
data2=read.table("LongJumpData.dat.txt",fill = T,skip = 1)
colnames(data2)=rep(c('Year','Performance'),4)
tidydata2=rbind(data2[,1:2],data2[,3:4],data2[,5:6],data2[,7:8])
tidydata2=tidydata2 %>% filter(!(is.na(Year)))%>%
  mutate(Year=Year+1900)
print(tidydata2)
summary(tidydata2)
```


(c)
```{r}
data3=read.table("BrainandBodyWeight.dat.txt",fill = T,skip = 1)
colnames(data3)=rep(c('BrainW','BodyW'),3)
tidydata3=rbind(data3[,1:2],data3[,3:4],data3[,5:6])
tidydata3=tidydata3 %>% filter(!(is.na(BrainW)))
print(tidydata3)
summary(tidydata3)
```


(d)
```{r}
Ife1=c(16.1,15.3,17.5)
Ife2=c(16.6,19.2,18.5)
Ife3=c(20.8,18.0,21.0)
PED1=c(8.1,8.6,10.1)
PED2=c(12.7,13.7,11.5)
PED3=c(14.4,15.4,13.7)
Yield=c(Ife1,Ife2,Ife3,PED1,PED2,PED3)
treatments=c(rep(1,3),rep(2,3),rep(3,3),rep(4,3),rep(5,3),rep(6,3))
tidydata4=cbind(Yield,treatments)
print(tidydata4)
```


